### ISSUE TITLE
Feature Request : Identify / mark videos for people who don't hold their phone the right way

### ISSUE THREAD

**Issue by d0gbrrt** [ThePatr10t/yall-Qaeda#21]
Enhancement Request for usability and identification of users who don't know correct manner documenting events with cell phone videography. 

Background : This is a known issue where users create videos with crappy video quality, due to recording video while holding cell phone in vertical position. 

This is a sign of ignorance and lack of caring for the end user and end users level of enjoyment when watching people doing stupid things on the internet. 

![cell_video_tutorial](https://user-images.githubusercontent.com/77515801/104787520-b084cb80-575d-11eb-8e04-9964ca3143a4.png)

**Comment by SirSchmo** [comment]
as the CEO of Schmo Corp. I fully back this feature.

**Comment by ThePatr10t** [comment]
Reminder : These are Trump supporters we're talking about ;)

**Comment by juanpc2018** [comment]
i think your post is insane...
Hands wrist was Not designed for wide angle, 
virtual buttons neither...

Cell phones should be "smarter" and have a button to rotate the sensor, Not the entire phone.. thats crazy...
its like rotating the entire house to screw a light bulb. LOL Jajajaja

or instead of rotating the entire sensor, to use a square sensor, like old 6x6 analog film cameras or modern Digital Backs.
people can select the wide angle they want: 
1.77:1  "Standard FullHD 1920x1080 or UltraHD 3840x2160, and ignore the other pixels...
more wide angle... Super 35mm 1.333:1, Widescreen 1:85:1, Techniscope 2.39:1, Anamorphic, etc...
1.8:1  1920x1066
1.8:1  1944x1080 
1.9:1  1920x1010
1.9:1  2052x1080
2.0:1  1920x960
2.0:1  2160x1080
2.1:1  1920x914
2.1:1  2268x1080
2.2:1  1920x872
2.2:1  2376x1080
2.39:1  1920x803
2.39:1  2581x1080

or less, like NTSC 4:3 640x480 
but more pixels.... 
960x720, 
1440x1080, 
2880x2160

35mm Academy Cine Format: 
21.95mm x 18.6mm
1.18:1

35mm Analog photo camera: 
36mm x 24mm 
1.5:1

IMAX different than 6x6 analog film cameras.
70mm x 48.5
1.44:1
ej:
1555x1080
1920x1333
3110x2160
3840x2666
6220x4320
7680x5333

https://en.wikipedia.org/wiki/35_mm_movie_film
https://en.wikipedia.org/wiki/IMAX
https://en.wikipedia.org/wiki/135_film
https://en.wikipedia.org/wiki/Super_35

OR....
Rotate the Computer Monitor...
https://www.apple-forever.com/pix_big/34.jpg
https://cdn.cultofmac.com/wp-content/uploads/2017/03/1988_RadiusFPD.png
https://cdn.cultofmac.com/wp-content/uploads/2017/03/display_portrait.jpg
https://photos5.appleinsider.com/gallery/33961-60483-Pro-Display-XDR-Vertical-Orientation-xl.jpg

**Comment by juanpc2018** [comment]
Reminder : Typical Left supporters we're talking about ;)  LOL Jajajajaja

**Comment by d0gbrrt** [comment]
Right, Left... same difference... 
If this is the best the parties can offer, We need a 3rd option.
Just sayin...

![1-e9UGA1jP7HgvPYDkRR3F3w](https://user-images.githubusercontent.com/77515801/104982702-36607b00-59d9-11eb-9d9a-359c8b1025fa.jpeg)
